inno_lib/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('documents/', views.DocumentListView.as_view(), name='documents'),
    path('document/<int:pk>', views.DocumentDetailView.as_view(), name='document-detail'),
    path('my/', views.LoanedDocumentsByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBooksForLibrarianListView.as_view(), name='all-borrowed'),
    path('document/<uuid:pk>/new/', views.renew_document_librarian, name='renew-document-librarian'),
    path('document/<uuid:pk>/claim/', views.claim_document, name='claim-document'),
    path('document/<uuid:pk>/return/', views.return_document, name='return-document')
]

itp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ # add links to pages:
    path('', include('inno_lib.urls')), # init page
    path('admin/', admin.site.urls), # admin mode
    path('reg_auth/', include('reg_auth.urls')), # authorization page
]

inno_lib/models/author.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    """
    Model representing an Author
    """
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """
        :return: the url to access a particular Author.
        """
        return reverse('author-detail', args=str(self.id))

    def __str__(self):
        return '{1}, {0}'.format(self.first_name, self.last_name)

inno_lib/models/document_models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

from inno_lib.models.author import Author
from inno_lib.models.tag import Tag

import uuid
import datetime


class Document(models.Model):
    """
    Model representing any Document in a system (but not a specific copy of one).
    """
    title = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    authors = models.ManyToManyField(
        Author,
        help_text='Add authors for this book',
    )
    tags = models.ManyToManyField(
        Tag,
        help_text='Add tags for this book',
    )

    def get_absolute_url(self):
        """
        :return: the url to access a particular Document instance.
        """
        return reverse('document-detail', args=[str(self.id)])

    def __str__(self):
        return self.title

    def display_authors(self):
        """
        Creates a string for the list of authors.
        :return: string of authors.
        """
        return ''.join([str(author) for author in self.authors.all()])

    def display_tags(self):
        """
        Creates a string for the list of tags
        :return: string of tags
        """
        return ''.join([tag.name for tag in self.tags.all()])

    def display_price(self):
        """
        :return: string representation of price.
        """
        return self.price


class Book(Document):
    """
    Model represents general book.
    """
    publisher = models.CharField(max_length=100)
    edition = models.IntegerField(default=1)
    is_bestseller = models.BooleanField(default=False)


class Article(Document):
    editor = models.CharField(max_length=100)
    journal = models.CharField(max_length=100)


# TODO: need to decide how to store files in database, then implement next 2 classes

class Audio(Document):
    content = models.CharField(max_length=200)


class Video(Document):
    content = models.CharField(max_length=200)


class DocumentInstance(models.Model):
    """
    Model representing a particular copy of the book (i. e. it can be borrowed from the library)
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this book for the whole lib')
    document = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True)
    # imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Document availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (('can_mark_returned', 'Set book as returned'),)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '{0} ({1})'.format(self.id, self.document.title)

    @property
    def is_overdue(self): # Check if current document if overdue
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def get_due_delta(self): # deadline depends on type of user
        delta = 0
        if getattr(self.document, 'book') is not None:
            if self.borrower.groups.first().name == 'Faculty':
                delta = 4
            elif self.document.book.is_bestseller:
                delta = 2
            else:
                delta = 3
        else:
            if self.borrower.groups.first().name == 'Students':  # For students
                delta = 2
            else:
                delta = 3

        return datetime.timedelta(weeks=delta)

inno_lib/models/tag.py
from django.db import models


class Tag(models.Model):
    """
    Model representing a Tag (e.g. 'funny', 'scary' etc.).
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

inno_lib/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
      
     
import datetime



class RenewDocumentForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 3 weeks (default 2).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=3):
            raise ValidationError(_('Invalid date - renewal more than 3 weeks ahead'))

        return data 

inno_lib/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import permission_required

from inno_lib.models.document_models import Document, DocumentInstance
from inno_lib.models.author import Author
from .forms import RenewDocumentForm

import datetime


def index(request):
    """
    View function for home page of site.
    """
    num_docs = Document.objects.all().count()
    num_instances = DocumentInstance.objects.all().count() # number of copies of this document
    num_instances_available = DocumentInstance.objects.filter(status__exact='a').count() # number of available copies of this document
    num_authors = Author.objects.count() # number of authors

    # Number of visit to this view, as counted in session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={'num_docs': num_docs, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available,
                 'num_authors': num_authors, 'num_visits': num_visits},
    )


class DocumentListView(generic.ListView):
    """
    Generic class-based view listing all documents in the system.
    """
    model = Document
    paginate_by = 5


class DocumentDetailView(generic.DetailView):
    """
    Generic class-based view the particular document page.
    """
    model = Document


# TODO: redirect to login page if not logged in
class LoanedDocumentsByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing documents to the current user.
    """
    model = DocumentInstance
    template_name = 'inno_lib/documentinstance_list_borrowed_user.html'
    paginate_by = 5

    def get_queryset(self):
        return DocumentInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@permission_required('inno_lib.can_mark_returned')
def renew_document_librarian(requset, pk):
    """
    Functional view describing the logic of renewing document instance by librarian.
    :param requset: HTTP request.
    :param pk: primary key for the DocumentInstance (truly, UUID).
    :return: rendered HTML.
    """
    docinst = get_object_or_404(DocumentInstance, pk=pk)

    # If this is a POST request then process the Form data
    if requset.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewDocumentForm(requset.POST)

        # Check if the form is valid:
        if form.is_valid():
            docinst.due_back = form.cleaned_data['renewal_date']
            docinst.save()
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=2)
        form = RenewDocumentForm(initial={'renewal_date': proposed_renewal_date,})

    return render(requset, 'inno_lib/document_renew_librarian.html', {'form': form, 'docinst': docinst})


class BorrowedBooksForLibrarianListView(PermissionRequiredMixin, generic.ListView):
    """
    Genereic class-based view listing all borrowed documents to the librarian.
    """
    permission_required = 'inno_lib.can_mark_returned'
    model = DocumentInstance
    template_name = 'inno_lib/documentinstance_list_borrowed_librarian.html'

    def get_queryset(self):
        return DocumentInstance.objects.filter(status__exact='o').order_by('due_back')


# def get_due_delta(user, document_instance):
#     return datetime.timedelta(weeks=3)


def claim_document(request, pk): # Claim the document with id = pk
    """
    Function-based view that allows authorized user to borrow a document.
    :param request:
    :param pk:
    :return:
    """
    instance = DocumentInstance.objects.get(id=pk) # Find such instance

    if instance is None: # If there's no such instance
        raise ValueError('No document instance with id {}'.format(pk)) # ERROR

    if instance.status != 'a': # If this instance is not available now
        raise ValueError('Document {} is not available for loan (has status {})'.format(pk, instance.status)) # ERROR (We cannot claim it)


    instance.status = 'o' # Set current status as 'On loan'
    instance.borrower = request.user # set current user as borrower
    # instance.due_back = datetime.date.today() + get_due_delta(request.user, instance)
    instance.due_back = datetime.date.today() + instance.get_due_delta()

    instance.save()

    # TODO: fix XSS
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# TODO: this shouldn't be pushed
def return_document(request, pk):  # return the document with id = pk
    instance = DocumentInstance.objects.get(id=pk)

    if instance is None: # If there's no such document
        raise ValueError('No document instance with id {}'.format(pk)) # ERROR

    if instance.status != 'o': # If this docunment is not 'On loan'
        raise ValueError('Document {} is not on loan (has status{})'.format(pk, instance.status)) # We cannot return 'on loan' document

    if instance.borrower.id != request.user.id: # if user doesn't coincide the book
        raise ValueError('Document {} is not borrowed by current user (current user id: {}, borrowed user id: {})' # ERROR
                         .format(pk, request.user.id, instance.borrower.id))

    instance.status = 'a' # Set statuc of current document as 'Available'
    instance.borrower = None # Remove borrower
    instance.due_back = None # Remove deadline

    instance.save()

    # TODO: fix XSS
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

inno_lib/templates/inno_lib/document_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ document.title }}</h1>

  <p><strong>Author:</strong> <a href=""> {% for author in document.authors.all %} {{ author }} {% if not forloop.last %}, {% endif %}{% endfor %}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Tags:</strong> {% for tag in document.tags.all %} {{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <p><strong>Price:</strong> {{ document.price }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in document.documentinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
        {% if copy.status == 'a' %}<a class="btn btn-success" href="{% url 'claim-document' copy.id %}">Claim</a> {% endif %}
        {% if copy.status == 'o' %}<a class="btn btn-primary" href="{% url 'return-document' copy.id %}">Return</a> {% endif %}
    {% endfor %}

  </div>
{% endblock %}

inno_lib/templates/inno_lib/document_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Document List</h1>

    {% if document_list %}
    <ul>
      {% for doc in document_list %}
      <li>
        <a href="{{ doc.get_absolute_url }}">{{ doc.title }}</a> ({{doc.display_authors}})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no documents in the library.</p>
    {% endif %}

{% endblock %}

inno_lib/templates/inno_lib/document_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{docinst.document.title}}</h1>
    <p>Borrower: {{docinst.borrower}}</p>
    <p{% if docinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{docinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

inno_lib/templates/inno_lib/documentinstance_list_borrowed_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All borrowed documents</h1>

    {% if documentinstance_list %}
    <ul>

      {% for docinst in documentinstance_list %}
      <li class="{% if docinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'document-detail' docinst.document.id %}">{{docinst.document.title}}</a> ({{ docinst.due_back }}) - {{ docinst.borrower }}
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-document-librarian' docinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no documents borrowed.</p>
    {% endif %}
{% endblock %}

inno_lib/templates/inno_lib/documentinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed documents</h1>

    {% if documentinstance_list %}
    <ul>

      {% for docinst in documentinstance_list %}
      <li class="{% if docinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'document-detail' docinst.document.id %}">{{docinst.document.title}}</a> ({{ docinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no documents borrowed.</p>
    {% endif %}
{% endblock %}